services:
  - type: web
    name: top-suite2
    env: python
    buildCommand: bash build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

